[project]
name = 'Decentralized-Identity-and-Access-Management-DIAM'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.access-control]
path = 'contracts/access-control.clar'
clarity_version = 2
epoch = 2.5

[contracts.auth-integration]
path = 'contracts/auth-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.verifiable-credentials]
path = 'contracts/verifiable-credentials.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
